<?php

namespace Database\Seeders;

use App\Models\DoctorList;
use Illuminate\Database\Seeder;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $doctor_list = array(
            array('id' => '1','doctor_id' => 'RX-DR-1','name' => 'Dr Udoy Shanker','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '2','doctor_id' => 'RX-DR-2','name' => 'Dr Morshedur Rahman','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '3','doctor_id' => 'RX-DR-3','name' => 'Dr Mahmub Morshed','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '4','doctor_id' => 'RX-DR-4','name' => 'Dr G. K. M. Shahiduzzaman','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '5','doctor_id' => 'RX-DR-5','name' => 'Dr Amar Biswas','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '6','doctor_id' => 'RX-DR-6','name' => 'Dr Sohel Rana','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '7','doctor_id' => 'RX-DR-7','name' => 'Dr A. H. M. Feroz','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '8','doctor_id' => 'RX-DR-8','name' => 'Dr Dipankar Kumar Mondol','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '9','doctor_id' => 'RX-DR-9','name' => 'Dr M. M. Monzur Hasan','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '10','doctor_id' => 'RX-DR-10','name' => 'Dr Md. Humayun Kabir Mintu','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '11','doctor_id' => 'RX-DR-11','name' => 'Dr Aminul Islam','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '12','doctor_id' => 'RX-DR-12','name' => 'Dr Md. Azizul Bari','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '13','doctor_id' => 'RX-DR-13','name' => 'Dr Nazibur Rahman Khandaker','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '14','doctor_id' => 'RX-DR-14','name' => 'Dr Monzur Quader','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '15','doctor_id' => 'RX-DR-15','name' => 'Dr Kamruzzaman','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '16','doctor_id' => 'RX-DR-16','name' => 'Dr Zakir','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '17','doctor_id' => 'RX-DR-17','name' => 'Dr S.M. Saiful','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '18','doctor_id' => 'RX-DR-18','name' => 'Dr Nurul Alam Talukder','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '19','doctor_id' => 'RX-DR-19','name' => 'Dr Shahin Wadud','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '20','doctor_id' => 'RX-DR-20','name' => 'Dr Bijoy Krishna Das','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '21','doctor_id' => 'RX-DR-21','name' => 'Dr S. K. Saha','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '22','doctor_id' => 'RX-DR-22','name' => 'Dr Jalal Uddin Iqbal','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '23','doctor_id' => 'RX-DR-23','name' => 'Dr Didar Uddin','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '24','doctor_id' => 'RX-DR-24','name' => 'Dr Tofail Ahmed','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '25','doctor_id' => 'RX-DR-25','name' => 'Dr Sufiya','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '26','doctor_id' => 'RX-DR-26','name' => 'Dr Sukriti Das','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '27','doctor_id' => 'RX-DR-27','name' => 'Dr Md. Aiyub Ali','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '28','doctor_id' => 'RX-DR-28','name' => 'Dr Anwarul Hossain','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '29','doctor_id' => 'RX-DR-29','name' => 'Dr A. B. M. Mahbubul Alam','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '30','doctor_id' => 'RX-DR-30','name' => 'Dr Kazi Shahnur Alam','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '31','doctor_id' => 'RX-DR-31','name' => 'Dr Atikuzzaman Rinku','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '32','doctor_id' => 'RX-DR-32','name' => 'Dr Md. Badrul Alam','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '33','doctor_id' => 'RX-DR-33','name' => 'Dr Rakib','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '34','doctor_id' => 'RX-DR-34','name' => 'Dr Md. Anwarul Haque','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '35','doctor_id' => 'RX-DR-35','name' => 'Dr Md. Rashed Anowar','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '36','doctor_id' => 'RX-DR-36','name' => 'Dr Debasish','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '37','doctor_id' => 'RX-DR-37','name' => 'Dr Suvo','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '38','doctor_id' => 'RX-DR-38','name' => 'Dr Abu Noim','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '39','doctor_id' => 'RX-DR-39','name' => 'Dr Mustafizur Rahman','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '40','doctor_id' => 'RX-DR-40','name' => 'Dr Mizanur Rahman','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '41','doctor_id' => 'RX-DR-41','name' => 'Dr Hasan Mahmud','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '42','doctor_id' => 'RX-DR-42','name' => 'Dr Sathi Das','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '43','doctor_id' => 'RX-DR-43','name' => 'Dr Jakir','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '44','doctor_id' => 'RX-DR-44','name' => 'Dr Md. Abdur Razzak','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '45','doctor_id' => 'RX-DR-45','name' => 'Dr Nafiur Imtiaz','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '46','doctor_id' => 'RX-DR-46','name' => 'Dr Mizan','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '47','doctor_id' => 'RX-DR-47','name' => 'Dr Imrul Anowar','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '48','doctor_id' => 'RX-DR-48','name' => 'Dr Abdus Salam Osmani','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '49','doctor_id' => 'RX-DR-49','name' => 'Dr Ariful Islam Mazumder','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '50','doctor_id' => 'RX-DR-50','name' => 'Dr Nazia Afrin','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '51','doctor_id' => 'RX-DR-51','name' => 'Dr Mustafa kamal Rouf','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '52','doctor_id' => 'RX-DR-52','name' => 'Dr Daudul Islam','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '53','doctor_id' => 'RX-DR-53','name' => 'Dr Shahin Sultana','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '54','doctor_id' => 'RX-DR-54','name' => 'Dr Lina Kazi','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '55','doctor_id' => 'RX-DR-55','name' => 'Dr H. M. Nazmul Hasan','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '56','doctor_id' => 'RX-DR-56','name' => 'Dr Aklakh Ahmed','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '57','doctor_id' => 'RX-DR-57','name' => 'Dr Sarwar Milon','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '58','doctor_id' => 'RX-DR-58','name' => 'Dr Baijeed Hasan','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '59','doctor_id' => 'RX-DR-59','name' => 'Dr Mosabbri Ahmed','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '60','doctor_id' => 'RX-DR-60','name' => 'Dr Amzad Hossain','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '61','doctor_id' => 'RX-DR-61','name' => 'Dr Anurova Pal','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '62','doctor_id' => 'RX-DR-62','name' => 'Dr Amran Sarkar','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '63','doctor_id' => 'RX-DR-63','name' => 'Dr Hanif Mohammad','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '64','doctor_id' => 'RX-DR-64','name' => 'Dr Jahangir Khaled','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '65','doctor_id' => 'RX-DR-65','name' => 'Dr Mir Mahfuzul Haque','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '66','doctor_id' => 'RX-DR-66','name' => 'Dr Ratan Das Gupta','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '67','doctor_id' => 'RX-DR-67','name' => 'Dr Nina Islam','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '68','doctor_id' => 'RX-DR-68','name' => 'Dr Kamrunnahar','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '69','doctor_id' => 'RX-DR-69','name' => 'Dr Rezoanul Haque Bul Bul','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '70','doctor_id' => 'RX-DR-70','name' => 'Dr Atiqur Rahman','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '71','doctor_id' => 'RX-DR-71','name' => 'Dr Alamgir Hossain','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '72','doctor_id' => 'RX-DR-72','name' => 'Dr Jewel Haque','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '73','doctor_id' => 'RX-DR-73','name' => 'Dr Nasir','mobile_no' => '880','pso_ffc' => 'I23'),
            array('id' => '74','doctor_id' => 'RX-DR-74','name' => 'DrMUNTASIR MAMUN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '75','doctor_id' => 'RX-DR-75','name' => 'DR,.AZHARUL HOQ','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '76','doctor_id' => 'RX-DR-76','name' => 'DrMAHILA HAKIM','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '77','doctor_id' => 'RX-DR-77','name' => 'DrRATNA','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '78','doctor_id' => 'RX-DR-78','name' => 'DrNAZNIN AKHTER','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '79','doctor_id' => 'RX-DR-79','name' => 'Dr MORSHED BAKI','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '80','doctor_id' => 'RX-DR-80','name' => 'Dr BAKHTIAR AZAM','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '81','doctor_id' => 'RX-DR-81','name' => 'Dr HARUN OR RASHID','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '82','doctor_id' => 'RX-DR-82','name' => 'Dr SALAUDDIN AHMED','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '83','doctor_id' => 'RX-DR-83','name' => 'Dr  KABIRUZZAMAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '84','doctor_id' => 'RX-DR-84','name' => 'Dr PROVAT KUMAR','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '85','doctor_id' => 'RX-DR-85','name' => 'Dr FARHANA MOSLEUDDIN NANCY','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '86','doctor_id' => 'RX-DR-86','name' => 'Dr MOMTAJ SABEKA ','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '87','doctor_id' => 'RX-DR-87','name' => 'Dr AFSANA RAHIM','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '88','doctor_id' => 'RX-DR-88','name' => 'Dr SHOFIUL ISLAM','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '89','doctor_id' => 'RX-DR-89','name' => 'DrHM.IMRAN SARKER','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '90','doctor_id' => 'RX-DR-90','name' => 'Dr ATIQ','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '91','doctor_id' => 'RX-DR-91','name' => 'Dr ARIFUL ISLAM','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '92','doctor_id' => 'RX-DR-92','name' => 'Dr GOLAM SOGIR','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '93','doctor_id' => 'RX-DR-93','name' => 'Dr NAZRUL ISLAM','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '94','doctor_id' => 'RX-DR-94','name' => 'DrMAHMUDUL HASSAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '95','doctor_id' => 'RX-DR-95','name' => 'Dr SHAWKATUL  BARI','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '96','doctor_id' => 'RX-DR-96','name' => 'Dr MIRZA M. HAFIQUR RASHID','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '97','doctor_id' => 'RX-DR-97','name' => 'Dr MOHIUDDIN AHMED','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '98','doctor_id' => 'RX-DR-98','name' => 'DrMAGLIN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '99','doctor_id' => 'RX-DR-99','name' => 'DrZILLUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '100','doctor_id' => 'RX-DR-100','name' => 'Dr BALA','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '101','doctor_id' => 'RX-DR-101','name' => 'DrNAHIDUZZAMAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '102','doctor_id' => 'RX-DR-102','name' => 'Dr MIR JAMAL  UDDIN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '103','doctor_id' => 'RX-DR-103','name' => 'DrNAHID','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '104','doctor_id' => 'RX-DR-104','name' => 'DrMAMUN AHMED','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '105','doctor_id' => 'RX-DR-105','name' => 'Dr ABUL HASAN MUHAMMAD BASHAR','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '106','doctor_id' => 'RX-DR-106','name' => 'Dr AFZAL MOMIN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '107','doctor_id' => 'RX-DR-107','name' => 'Dr MAFUZA AKTAR','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '108','doctor_id' => 'RX-DR-108','name' => 'Dr AMANULLA BIN SIDDIK','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '109','doctor_id' => 'RX-DR-109','name' => 'DrPARITOSH KUMAR','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '110','doctor_id' => 'RX-DR-110','name' => 'DrMIRA','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '111','doctor_id' => 'RX-DR-111','name' => 'DrTANISHA','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '112','doctor_id' => 'RX-DR-112','name' => 'DrSAIDUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '113','doctor_id' => 'RX-DR-113','name' => 'DrJOBAYDA','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '114','doctor_id' => 'RX-DR-114','name' => 'DrREZWANUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '115','doctor_id' => 'RX-DR-115','name' => 'DrSNIKDHA','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '116','doctor_id' => 'RX-DR-116','name' => 'DrMIZANUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '117','doctor_id' => 'RX-DR-117','name' => 'DrTANVIR RAHMAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '118','doctor_id' => 'RX-DR-118','name' => 'DrREZAUL HAQUE','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '119','doctor_id' => 'RX-DR-119','name' => 'DR,.ENAYETUL ISLAM','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '120','doctor_id' => 'RX-DR-120','name' => 'DrJUNAYED','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '121','doctor_id' => 'RX-DR-121','name' => 'DrKOLLOL','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '122','doctor_id' => 'RX-DR-122','name' => 'DrKHAIRUL PATWARY','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '123','doctor_id' => 'RX-DR-123','name' => 'DrJALAL UDDIN ','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '124','doctor_id' => 'RX-DR-124','name' => 'DrNAZMUL ALAM','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '125','doctor_id' => 'RX-DR-125','name' => 'DrMD.KAMRUZZAMAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '126','doctor_id' => 'RX-DR-126','name' => 'DrHASSAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '127','doctor_id' => 'RX-DR-127','name' => 'DrRAFI','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '128','doctor_id' => 'RX-DR-128','name' => 'DrNAZMA AKHTER','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '129','doctor_id' => 'RX-DR-129','name' => 'DrZIAUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '130','doctor_id' => 'RX-DR-130','name' => 'DrRIAD','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '131','doctor_id' => 'RX-DR-131','name' => 'DrBALA','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '132','doctor_id' => 'RX-DR-132','name' => 'DrSHIRAJUL ISLAM','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '133','doctor_id' => 'RX-DR-133','name' => 'DrMEHEDI','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '134','doctor_id' => 'RX-DR-134','name' => 'DrHADI','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '135','doctor_id' => 'RX-DR-135','name' => 'DrSAJU','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '136','doctor_id' => 'RX-DR-136','name' => 'DrJAHID','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '137','doctor_id' => 'RX-DR-137','name' => 'DrREZWANA','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '138','doctor_id' => 'RX-DR-138','name' => 'DrRAFIQUL','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '139','doctor_id' => 'RX-DR-139','name' => 'DrMASUD RANA','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '140','doctor_id' => 'RX-DR-140','name' => 'DrANWER ISRAIL','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '141','doctor_id' => 'RX-DR-141','name' => 'DrTOUHIDUL','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '142','doctor_id' => 'RX-DR-142','name' => 'DrJUBAIDA NASRIN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '143','doctor_id' => 'RX-DR-143','name' => 'DR,ABEDA SULTANA','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '144','doctor_id' => 'RX-DR-144','name' => 'DrGURUDAS MONDOL','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '145','doctor_id' => 'RX-DR-145','name' => 'DrJEBUNNESSA','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '146','doctor_id' => 'RX-DR-146','name' => 'DrTARIN AHMED','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '147','doctor_id' => 'RX-DR-147','name' => 'DrAMIRUL HOQ','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '148','doctor_id' => 'RX-DR-148','name' => 'DrSHAWKAT ALI','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '149','doctor_id' => 'RX-DR-149','name' => 'DrMOBASSHER KHALIL','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '150','doctor_id' => 'RX-DR-150','name' => 'DrSHARMIN CHOWDHURY','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '151','doctor_id' => 'RX-DR-151','name' => 'DrMD.MAHMUDUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '152','doctor_id' => 'RX-DR-152','name' => 'DrAKM.MASUM KHAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '153','doctor_id' => 'RX-DR-153','name' => 'DrSHAWKAT ALI','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '154','doctor_id' => 'RX-DR-154','name' => 'DrNILA ISLAM','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '155','doctor_id' => 'RX-DR-155','name' => 'DrTARIQUL','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '156','doctor_id' => 'RX-DR-156','name' => 'DrTANVIR RAHMAN','mobile_no' => '880','pso_ffc' => 'I24'),
            array('id' => '157','doctor_id' => 'RX-DR-157','name' => 'Dr MD. HARUN OR RASHID','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '158','doctor_id' => 'RX-DR-158','name' => 'Dr SHAMIM AHMED','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '159','doctor_id' => 'RX-DR-159','name' => 'DrZAMANUL ISLAM BHUIYAN','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '160','doctor_id' => 'RX-DR-160','name' => 'DrZIA UDDIN AHMED','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '161','doctor_id' => 'RX-DR-161','name' => 'DrMD.SHAKIBUZZMAN AREFIN','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '162','doctor_id' => 'RX-DR-162','name' => 'DrMIZANUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '163','doctor_id' => 'RX-DR-163','name' => 'DrPRITOM CHOKROBARTY','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '164','doctor_id' => 'RX-DR-164','name' => 'MD.SAZZAD HOSAIN','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '165','doctor_id' => 'RX-DR-165','name' => 'DrSELINA AKTER','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '166','doctor_id' => 'RX-DR-166','name' => 'DrSAYED MAHBUB MORSHED','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '167','doctor_id' => 'RX-DR-167','name' => 'DrRAJU','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '168','doctor_id' => 'RX-DR-168','name' => 'Dr MOINUL ISLAM ','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '169','doctor_id' => 'RX-DR-169','name' => 'Dr AMIT SAHA','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '170','doctor_id' => 'RX-DR-170','name' => 'Dr SHAHINUR  ALAM','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '171','doctor_id' => 'RX-DR-171','name' => 'DrSARONIKA AKHTER PEU','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '172','doctor_id' => 'RX-DR-172','name' => 'DrRIAD BHUIYAN','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '173','doctor_id' => 'RX-DR-173','name' => 'Dr TANZINA AFROSE BOBY','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '174','doctor_id' => 'RX-DR-174','name' => 'DrTRISHA','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '175','doctor_id' => 'RX-DR-175','name' => 'DrMOSTAFIZUR TUHIN','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '176','doctor_id' => 'RX-DR-176','name' => 'Dr TANVIR AHMED ','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '177','doctor_id' => 'RX-DR-177','name' => 'Dr RUMANA','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '178','doctor_id' => 'RX-DR-178','name' => 'DrAEYASHA HOSSAIN SADIA','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '179','doctor_id' => 'RX-DR-179','name' => 'Dr MONJURUL MORSHED','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '180','doctor_id' => 'RX-DR-180','name' => 'Dr LIMON ','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '181','doctor_id' => 'RX-DR-181','name' => 'DrASIF CHOWDHURY','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '182','doctor_id' => 'RX-DR-182','name' => 'Dr KABIRUDDIN','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '183','doctor_id' => 'RX-DR-183','name' => 'DrMAHMUDUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '184','doctor_id' => 'RX-DR-184','name' => 'DrRAFI','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '185','doctor_id' => 'RX-DR-185','name' => 'DrNAZIM  KAYKOBAD','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '186','doctor_id' => 'RX-DR-186','name' => 'DrABDUL MALEK','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '187','doctor_id' => 'RX-DR-187','name' => 'DrQAYES BIN IQBAL','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '188','doctor_id' => 'RX-DR-188','name' => 'MR.TASNUBA AKHTER','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '189','doctor_id' => 'RX-DR-189','name' => 'DrSAIRA BANU MOMOTA','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '190','doctor_id' => 'RX-DR-190','name' => 'DrMONI','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '191','doctor_id' => 'RX-DR-191','name' => 'DrBAZLUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '192','doctor_id' => 'RX-DR-192','name' => 'DrMOSTAFA KAMAL ROUF','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '193','doctor_id' => 'RX-DR-193','name' => 'DrJANNAT ARA','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '194','doctor_id' => 'RX-DR-194','name' => 'DrRIFAYET','mobile_no' => '880','pso_ffc' => 'I26'),
            array('id' => '195','doctor_id' => 'RX-DR-195','name' => 'Dr Pizus Bissas','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '196','doctor_id' => 'RX-DR-196','name' => 'Dr Zillur Rahman','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '197','doctor_id' => 'RX-DR-197','name' => 'Dr, Nabil Ahmed','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '198','doctor_id' => 'RX-DR-198','name' => 'Dr Soumen Chy','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '199','doctor_id' => 'RX-DR-199','name' => 'Dr Mamunur Rashid Sikder','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '200','doctor_id' => 'RX-DR-200','name' => 'Dr Mahabubur Rahman','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '201','doctor_id' => 'RX-DR-201','name' => 'Dr Bulbul  Kabir','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '202','doctor_id' => 'RX-DR-202','name' => 'Dr Ashraful Alam Siam','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '203','doctor_id' => 'RX-DR-203','name' => 'Dr Santanu Kumar Gosh','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '204','doctor_id' => 'RX-DR-204','name' => 'Dr Zulfikar Ali ','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '205','doctor_id' => 'RX-DR-205','name' => 'Dr Abdul Momen','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '206','doctor_id' => 'RX-DR-206','name' => 'Dr ABM Nurnobi','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '207','doctor_id' => 'RX-DR-207','name' => 'Dr Md Touhiduzzaman','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '208','doctor_id' => 'RX-DR-208','name' => 'Dr Nirmal Kanti Chy','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '209','doctor_id' => 'RX-DR-209','name' => 'Dr Ferdous Wahid','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '210','doctor_id' => 'RX-DR-210','name' => 'Dr Farzana Rahman','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '211','doctor_id' => 'RX-DR-211','name' => 'Dr Mahfuzur Rahman Tomal','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '212','doctor_id' => 'RX-DR-212','name' => 'Dr Saik Md. Arif','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '213','doctor_id' => 'RX-DR-213','name' => 'Dr Apu','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '214','doctor_id' => 'RX-DR-214','name' => 'Dr MG Azam','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '215','doctor_id' => 'RX-DR-215','name' => 'Dr Zafrin Zahan','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '216','doctor_id' => 'RX-DR-216','name' => 'Dr Md. Safiqul Islam','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '217','doctor_id' => 'RX-DR-217','name' => 'Dr Shekhor Kumar Mondal','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '218','doctor_id' => 'RX-DR-218','name' => 'DrMoinul Islam','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '219','doctor_id' => 'RX-DR-219','name' => 'Dr Md Nobiul Islam','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '220','doctor_id' => 'RX-DR-220','name' => 'Dr Mizanur Rahman','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '221','doctor_id' => 'RX-DR-221','name' => 'Dr Minhaz Abedin','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '222','doctor_id' => 'RX-DR-222','name' => 'Dr Bijoy Dutta','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '223','doctor_id' => 'RX-DR-223','name' => 'Dr Ashraful Alam ','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '224','doctor_id' => 'RX-DR-224','name' => 'Dr Abid Al Jabed','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '225','doctor_id' => 'RX-DR-225','name' => 'Dr Riaz Kawsar','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '226','doctor_id' => 'RX-DR-226','name' => 'Dr Shariar Kabir','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '227','doctor_id' => 'RX-DR-227','name' => 'Dr Tanvir Ahmed','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '228','doctor_id' => 'RX-DR-228','name' => 'Dr Maksuda','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '229','doctor_id' => 'RX-DR-229','name' => 'Dr Faisal','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '230','doctor_id' => 'RX-DR-230','name' => 'Dr Asif Iqbal','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '231','doctor_id' => 'RX-DR-231','name' => 'Dr Kud-rat-e Hasan','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '232','doctor_id' => 'RX-DR-232','name' => 'Dr Israt Jahan','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '233','doctor_id' => 'RX-DR-233','name' => 'Dr Atahar Ali','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '234','doctor_id' => 'RX-DR-234','name' => 'Dr Nobojit Chy','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '235','doctor_id' => 'RX-DR-235','name' => 'Dr Suchorit Barua','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '236','doctor_id' => 'RX-DR-236','name' => 'Dr Mainul Islam','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '237','doctor_id' => 'RX-DR-237','name' => 'Dr Anwar Hossen','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '238','doctor_id' => 'RX-DR-238','name' => 'Dr Daniel ','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '239','doctor_id' => 'RX-DR-239','name' => 'Dr Anisul Gani Khan','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '240','doctor_id' => 'RX-DR-240','name' => 'Dr Joyanto Kumar Bisswas','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '241','doctor_id' => 'RX-DR-241','name' => 'Dr Sariful Islam','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '242','doctor_id' => 'RX-DR-242','name' => 'Dr Abul Kalam Azad','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '243','doctor_id' => 'RX-DR-243','name' => 'Dr Partho Protim Chy','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '244','doctor_id' => 'RX-DR-244','name' => 'Dr Shuvro Chakrabarti','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '245','doctor_id' => 'RX-DR-245','name' => 'Dr Abu Hena Reja Siddiki','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '246','doctor_id' => 'RX-DR-246','name' => 'Dr Hasan Alamgir','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '247','doctor_id' => 'RX-DR-247','name' => 'Dr Mejba Uddin','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '248','doctor_id' => 'RX-DR-248','name' => 'Dr Mahbubur Rahman','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '249','doctor_id' => 'RX-DR-249','name' => 'Dr AKM Monoarul Islam','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '250','doctor_id' => 'RX-DR-250','name' => 'Dr Billal Alam','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '251','doctor_id' => 'RX-DR-251','name' => 'Dr Tazin Afroz','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '252','doctor_id' => 'RX-DR-252','name' => 'Dr Amir Hossain','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '253','doctor_id' => 'RX-DR-253','name' => 'Dr Mohiuddin Osmani','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '254','doctor_id' => 'RX-DR-254','name' => 'Dr AKM Mojibur Rahman','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '255','doctor_id' => 'RX-DR-255','name' => 'Dr Kajol Kumar Karmokar','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '256','doctor_id' => 'RX-DR-256','name' => 'Dr Amal Kumar Chy','mobile_no' => '880','pso_ffc' => 'I28'),
            array('id' => '257','doctor_id' => 'RX-DR-257','name' => 'Dr Fazila Tun Nesa Malik','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '258','doctor_id' => 'RX-DR-258','name' => 'Dr Nazir Ahmed','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '259','doctor_id' => 'RX-DR-259','name' => 'Dr Md. Badiuzzaman','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '260','doctor_id' => 'RX-DR-260','name' => 'Dr Mir Nesaruddin Ahmed','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '261','doctor_id' => 'RX-DR-261','name' => 'Dr Ashok Kumar Dutta','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '262','doctor_id' => 'RX-DR-262','name' => 'Dr Dhiman Banik','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '263','doctor_id' => 'RX-DR-263','name' => 'Dr Md. Kabiruzzaman','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '264','doctor_id' => 'RX-DR-264','name' => 'DrHafizur Rahman','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '265','doctor_id' => 'RX-DR-265','name' => 'Dr Shamimur Rahman','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '266','doctor_id' => 'RX-DR-266','name' => 'Dr Md. Kalimuddin','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '267','doctor_id' => 'RX-DR-267','name' => 'Dr Tawfiq Shahriar Huq','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '268','doctor_id' => 'RX-DR-268','name' => 'Dr Golam Sarwer Tarek','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '269','doctor_id' => 'RX-DR-269','name' => 'Dr Md.Kawser Mostafa','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '270','doctor_id' => 'RX-DR-270','name' => 'Dr Mir Israquzzaman','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '271','doctor_id' => 'RX-DR-271','name' => 'Dr A.H.M Sarowar Hossain Chowdhury','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '272','doctor_id' => 'RX-DR-272','name' => 'Dr Quazi Shafiqul Islam','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '273','doctor_id' => 'RX-DR-273','name' => 'Dr Nazmun Laila','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '274','doctor_id' => 'RX-DR-274','name' => 'Dr Md. Arifur Rahman','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '275','doctor_id' => 'RX-DR-275','name' => 'Dr Md. Asaduzzaman','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '276','doctor_id' => 'RX-DR-276','name' => 'Dr Mahmudur Rahman','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '277','doctor_id' => 'RX-DR-277','name' => 'Dr Rafiqul Islam','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '278','doctor_id' => 'RX-DR-278','name' => 'Dr Esmat Ara','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '279','doctor_id' => 'RX-DR-279','name' => 'Dr Mohiuddin Mohin','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '280','doctor_id' => 'RX-DR-280','name' => 'DrArif ul Asif','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '281','doctor_id' => 'RX-DR-281','name' => 'DrNur Nahar Ayrin','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '282','doctor_id' => 'RX-DR-282','name' => 'Dr Shahidullah','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '283','doctor_id' => 'RX-DR-283','name' => 'Dr Smita Kanungo','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '284','doctor_id' => 'RX-DR-284','name' => 'Dr Washim Ahmed','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '285','doctor_id' => 'RX-DR-285','name' => 'Dr Tasfia Ahmed Tisha','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '286','doctor_id' => 'RX-DR-286','name' => 'Dr Anwarul Kabir Dipu','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '287','doctor_id' => 'RX-DR-287','name' => 'Dr Asaduzzaman Sadi','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '288','doctor_id' => 'RX-DR-288','name' => 'Dr Prosanto Kumar Chanda ','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '289','doctor_id' => 'RX-DR-289','name' => 'Dr Wahid Sadique Anik','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '290','doctor_id' => 'RX-DR-290','name' => 'Dr Afridi Rizvi','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '291','doctor_id' => 'RX-DR-291','name' => 'Dr Mostafa Kamal Khan','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '292','doctor_id' => 'RX-DR-292','name' => 'Dr Adrita Afzal','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '293','doctor_id' => 'RX-DR-293','name' => 'DrMohammad Alamgir','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '294','doctor_id' => 'RX-DR-294','name' => 'DrHumayra Nahar','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '295','doctor_id' => 'RX-DR-295','name' => 'Dr Nowshin Farzana','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '296','doctor_id' => 'RX-DR-296','name' => 'Dr Esratuzzahan','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '297','doctor_id' => 'RX-DR-297','name' => 'Dr Shuvo Shaha','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '298','doctor_id' => 'RX-DR-298','name' => 'Dr Nazrul Islam','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '299','doctor_id' => 'RX-DR-299','name' => 'Dr Maj Kamrul Islam','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '300','doctor_id' => 'RX-DR-300','name' => 'DrShams Afroz Ekra','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '301','doctor_id' => 'RX-DR-301','name' => 'Dr Faisal','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '302','doctor_id' => 'RX-DR-302','name' => 'DrTanvir Adnan','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '303','doctor_id' => 'RX-DR-303','name' => 'Dr Nahid Azhar','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '304','doctor_id' => 'RX-DR-304','name' => 'DrAbdur Rashid Shifat','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '305','doctor_id' => 'RX-DR-305','name' => 'Dr Salauddin Munna','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '306','doctor_id' => 'RX-DR-306','name' => 'Dr Jashim Jubayer','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '307','doctor_id' => 'RX-DR-307','name' => 'DrAkhtarun Nahar Akhi','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '308','doctor_id' => 'RX-DR-308','name' => 'Dr Kazi Alam Nowaz Juel','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '309','doctor_id' => 'RX-DR-309','name' => 'Dr Obayed Rahman','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '310','doctor_id' => 'RX-DR-310','name' => 'Dr Fayek Khandaker','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '311','doctor_id' => 'RX-DR-311','name' => 'Dr Mayen Hasan Sabbir','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '312','doctor_id' => 'RX-DR-312','name' => 'Dr Rehnuma Tawshin','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '313','doctor_id' => 'RX-DR-313','name' => 'Dr Shamim Ahmed Chowdhury.','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '314','doctor_id' => 'RX-DR-314','name' => 'Dr Mehedi Zaman','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '315','doctor_id' => 'RX-DR-315','name' => 'Dr Mamun Rashid','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '316','doctor_id' => 'RX-DR-316','name' => 'Dr Tania Sharmeen','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '317','doctor_id' => 'RX-DR-317','name' => 'Dr Shehab Hasan','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '318','doctor_id' => 'RX-DR-318','name' => 'Dr Mahbub Hasan','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '319','doctor_id' => 'RX-DR-319','name' => 'Dr Nazia Zareen','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '320','doctor_id' => 'RX-DR-320','name' => 'Dr DMA Kabir','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '321','doctor_id' => 'RX-DR-321','name' => 'Dr Habibur Rahman','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '322','doctor_id' => 'RX-DR-322','name' => 'DrAbdul Gafur','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '323','doctor_id' => 'RX-DR-323','name' => 'DrKhaled Mohsin','mobile_no' => '880','pso_ffc' => 'I31'),
            array('id' => '324','doctor_id' => 'RX-DR-324','name' => 'DrAHSAN HABIB','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '325','doctor_id' => 'RX-DR-325','name' => 'DrJEHAD KHAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '326','doctor_id' => 'RX-DR-326','name' => 'DrMUJIBUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '327','doctor_id' => 'RX-DR-327','name' => 'DrZAKIR HOSSAIN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '328','doctor_id' => 'RX-DR-328','name' => 'DrFERDOUS KHAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '329','doctor_id' => 'RX-DR-329','name' => 'DrANISUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '330','doctor_id' => 'RX-DR-330','name' => 'PROF. Dr MD. ENAMUL KARIM','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '331','doctor_id' => 'RX-DR-331','name' => 'Dr SARWAR IQBAL','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '332','doctor_id' => 'RX-DR-332','name' => 'Dr MD. TITU MIAH','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '333','doctor_id' => 'RX-DR-333','name' => 'Dr KHANDAKER QAMRUL ISLAM','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '334','doctor_id' => 'RX-DR-334','name' => 'PROF. Dr A S M A RAIHAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '335','doctor_id' => 'RX-DR-335','name' => 'Dr SAUMITRA  SARKAR','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '336','doctor_id' => 'RX-DR-336','name' => 'Dr MD. RAFIQUL ALAM','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '337','doctor_id' => 'RX-DR-337','name' => 'PROF. Dr TASLIM UDDIN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '338','doctor_id' => 'RX-DR-338','name' => 'Dr MIRZA AZIZUL HAQUE','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '339','doctor_id' => 'RX-DR-339','name' => 'PROF. Dr NIZAM UDDIN CHOWDHURY','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '340','doctor_id' => 'RX-DR-340','name' => 'Dr MD. MONIRUZZAMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '341','doctor_id' => 'RX-DR-341','name' => 'PROF. Dr MD. SHAFIUDDIN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '342','doctor_id' => 'RX-DR-342','name' => 'PROF. Dr FARID UDDIN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '343','doctor_id' => 'RX-DR-343','name' => 'Dr NAZRUL ISLAM','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '344','doctor_id' => 'RX-DR-344','name' => 'PROF. KANAK KANTI BARUA','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '345','doctor_id' => 'RX-DR-345','name' => 'PROF. Dr KHAN ABUL KALAM AZAD','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '346','doctor_id' => 'RX-DR-346','name' => 'PROF. QUAZI TARIKUL ISLAM','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '347','doctor_id' => 'RX-DR-347','name' => 'Dr MONIRUZAMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '348','doctor_id' => 'RX-DR-348','name' => 'PROF. SHAMIM AHMED','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '349','doctor_id' => 'RX-DR-349','name' => 'ASSO. PROF. DELWAR HOSSAIN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '350','doctor_id' => 'RX-DR-350','name' => 'PROF. Dr M N NAG','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '351','doctor_id' => 'RX-DR-351','name' => 'PROF. Dr HABIBUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '352','doctor_id' => 'RX-DR-352','name' => 'ASST. PROF. MD GOLAM KIBRIA KHAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '353','doctor_id' => 'RX-DR-353','name' => 'Dr MOHAMMAD HOSSAIN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '354','doctor_id' => 'RX-DR-354','name' => 'ASSO. PROF. HASAN ZAHIDUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '355','doctor_id' => 'RX-DR-355','name' => 'PROF. M. MUHIBUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '356','doctor_id' => 'RX-DR-356','name' => 'PROF. Dr A H M ROWSHON','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '357','doctor_id' => 'RX-DR-357','name' => 'ASST. PROF. NARAYAN CHANDRA KUNDO','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '358','doctor_id' => 'RX-DR-358','name' => 'PROF. Dr  M A  AZAHAR','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '359','doctor_id' => 'RX-DR-359','name' => 'PROF. Dr SAYED WAHIDUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '360','doctor_id' => 'RX-DR-360','name' => 'PROF. S.K. SADER HOSSAIN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '361','doctor_id' => 'RX-DR-361','name' => 'PROF. Dr H.A.M. NAZMUL AHSAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '362','doctor_id' => 'RX-DR-362','name' => 'ASSO. PROF. Dr H S FERDOUS','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '363','doctor_id' => 'RX-DR-363','name' => 'Dr HURJAHAN URMEE','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '364','doctor_id' => 'RX-DR-364','name' => 'PROF. Dr MD. ZIAUL HAQUE','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '365','doctor_id' => 'RX-DR-365','name' => 'ASST. PROF. Dr MD. MOHSIN HOSSAIN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '366','doctor_id' => 'RX-DR-366','name' => 'ASST. PROF. Dr ABDULLAH AL MAMUN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '367','doctor_id' => 'RX-DR-367','name' => 'PROF. Dr ATAUR RAHMAN CHY','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '368','doctor_id' => 'RX-DR-368','name' => 'Dr MD. RUMMANA BARI','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '369','doctor_id' => 'RX-DR-369','name' => 'PROF. Dr MD. ABDUR ROHIM','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '370','doctor_id' => 'RX-DR-370','name' => 'Dr KAMRUZZAMAN MD JAHIR','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '371','doctor_id' => 'RX-DR-371','name' => 'DrASHIQUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '372','doctor_id' => 'RX-DR-372','name' => 'PROF. Dr TOUHIDUL HAQUE','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '373','doctor_id' => 'RX-DR-373','name' => 'Dr AMIR HOSSAIN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '374','doctor_id' => 'RX-DR-374','name' => 'Dr MOHAMMAD AKTERUZZAMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '375','doctor_id' => 'RX-DR-375','name' => 'Dr REZWANUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '376','doctor_id' => 'RX-DR-376','name' => 'Dr IQBAL AHMED','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '377','doctor_id' => 'RX-DR-377','name' => 'Dr TAREQ','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '378','doctor_id' => 'RX-DR-378','name' => 'Dr SIBLY MD AMINUL EHSAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '379','doctor_id' => 'RX-DR-379','name' => 'Dr EMATUDOULA RUBEL','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '380','doctor_id' => 'RX-DR-380','name' => 'Dr ASHRAFUZZAMAN SAIKOT','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '381','doctor_id' => 'RX-DR-381','name' => 'Dr KASFIA JALIL','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '382','doctor_id' => 'RX-DR-382','name' => 'DrKAMRUZZAMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '383','doctor_id' => 'RX-DR-383','name' => 'Dr ABU SADAT YOUSUF','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '384','doctor_id' => 'RX-DR-384','name' => 'Dr RAZIB SAHA','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '385','doctor_id' => 'RX-DR-385','name' => 'Dr SADIA AFRIN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '386','doctor_id' => 'RX-DR-386','name' => 'Dr JESSY','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '387','doctor_id' => 'RX-DR-387','name' => 'Dr UMMEY SALMA','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '388','doctor_id' => 'RX-DR-388','name' => 'Dr AFM SAIDUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '389','doctor_id' => 'RX-DR-389','name' => 'Dr TAREQ ALOM','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '390','doctor_id' => 'RX-DR-390','name' => 'Dr ASIF','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '391','doctor_id' => 'RX-DR-391','name' => 'Dr FAFAT','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '392','doctor_id' => 'RX-DR-392','name' => 'Dr SHARIF','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '393','doctor_id' => 'RX-DR-393','name' => 'Dr PROVA','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '394','doctor_id' => 'RX-DR-394','name' => 'Dr NAYAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '395','doctor_id' => 'RX-DR-395','name' => 'Dr SHOPNIL','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '396','doctor_id' => 'RX-DR-396','name' => 'Dr ADNAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '397','doctor_id' => 'RX-DR-397','name' => 'Dr RIFAT','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '398','doctor_id' => 'RX-DR-398','name' => 'DrSHELLY JAHAN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '399','doctor_id' => 'RX-DR-399','name' => 'Dr BORNA','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '400','doctor_id' => 'RX-DR-400','name' => 'Dr RIYA','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '401','doctor_id' => 'RX-DR-401','name' => 'Dr NADIA','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '402','doctor_id' => 'RX-DR-402','name' => 'Dr PIA','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '403','doctor_id' => 'RX-DR-403','name' => 'Dr RUBY','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '404','doctor_id' => 'RX-DR-404','name' => 'Dr ASIF','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '405','doctor_id' => 'RX-DR-405','name' => 'Dr DANIYAL','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '406','doctor_id' => 'RX-DR-406','name' => 'Dr MIM','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '407','doctor_id' => 'RX-DR-407','name' => 'Dr ORCHI','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '408','doctor_id' => 'RX-DR-408','name' => 'Dr FASHA','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '409','doctor_id' => 'RX-DR-409','name' => 'Dr OPU','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '410','doctor_id' => 'RX-DR-410','name' => 'Dr KAUSHIK','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '411','doctor_id' => 'RX-DR-411','name' => 'Dr TONMOY','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '412','doctor_id' => 'RX-DR-412','name' => 'Dr WRITTIKA','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '413','doctor_id' => 'RX-DR-413','name' => 'Dr TASIN','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '414','doctor_id' => 'RX-DR-414','name' => 'Dr TASNIM','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '415','doctor_id' => 'RX-DR-415','name' => 'Dr NAJIA','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '416','doctor_id' => 'RX-DR-416','name' => 'Dr SAMANTHA','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '417','doctor_id' => 'RX-DR-417','name' => 'Dr WASEQ','mobile_no' => '880','pso_ffc' => 'I33'),
            array('id' => '418','doctor_id' => 'RX-DR-418','name' => 'PROF. Dr M.A. SAMAD','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '419','doctor_id' => 'RX-DR-419','name' => 'PROF. RAZIA SULTANA','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '420','doctor_id' => 'RX-DR-420','name' => 'Dr SAED ALI AHSAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '421','doctor_id' => 'RX-DR-421','name' => 'Dr A P M SOHRABUZZAMAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '422','doctor_id' => 'RX-DR-422','name' => 'Dr M A HASNAT','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '423','doctor_id' => 'RX-DR-423','name' => 'Dr LUTFAR RAHMAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '424','doctor_id' => 'RX-DR-424','name' => 'PROF. KHWAZA NAZIMUDDIN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '425','doctor_id' => 'RX-DR-425','name' => 'PROF. Dr ASIA KHANOM','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '426','doctor_id' => 'RX-DR-426','name' => 'PROF. RAIQUL ALAM','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '427','doctor_id' => 'RX-DR-427','name' => 'PROF. AZHARUL HAQUE','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '428','doctor_id' => 'RX-DR-428','name' => 'PROF. JAHARUL ALAM KHAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '429','doctor_id' => 'RX-DR-429','name' => 'PROF. ABDUL WADUD CHOWDHURY','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '430','doctor_id' => 'RX-DR-430','name' => 'Dr MAHABUBUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '431','doctor_id' => 'RX-DR-431','name' => 'DrNURUN NAHAR FATEMA','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '432','doctor_id' => 'RX-DR-432','name' => 'Dr LOKMAN HOSSAIN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '433','doctor_id' => 'RX-DR-433','name' => 'MD. MOHSIN ','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '434','doctor_id' => 'RX-DR-434','name' => ' Dr ASRAF ALI','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '435','doctor_id' => 'RX-DR-435','name' => 'PROF. MONZUR RAHMAN GALIB','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '436','doctor_id' => 'RX-DR-436','name' => 'PROF. REDWANUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '437','doctor_id' => 'RX-DR-437','name' => 'Dr FIROZ AMIN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '438','doctor_id' => 'RX-DR-438','name' => 'PROF. MOSTAFA ZAMAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '439','doctor_id' => 'RX-DR-439','name' => 'PROF. AFZALUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '440','doctor_id' => 'RX-DR-440','name' => 'PROF. BAREN CHAKRABORTI','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '441','doctor_id' => 'RX-DR-441','name' => 'PROF. MONSUR HABIB ','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '442','doctor_id' => 'RX-DR-442','name' => 'PROF. ABU NASAR RIZVI ','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '443','doctor_id' => 'RX-DR-443','name' => 'PROF. ABDUZ ZAHER','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '444','doctor_id' => 'RX-DR-444','name' => 'PROF. M.A. FAIZ','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '445','doctor_id' => 'RX-DR-445','name' => 'Dr INDROZIT PROSHAD ','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '446','doctor_id' => 'RX-DR-446','name' => 'PROF. Dr SAMIREN KUMAR SAHA','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '447','doctor_id' => 'RX-DR-447','name' => 'PROF. Dr ABDUL JALIL CHOW','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '448','doctor_id' => 'RX-DR-448','name' => 'PROF. Dr M.A. HANNAN ','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '449','doctor_id' => 'RX-DR-449','name' => 'PROF. SIRAJUL HAQUE','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '450','doctor_id' => 'RX-DR-450','name' => 'Dr MOKADDAS HOSSAIN SADI','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '451','doctor_id' => 'RX-DR-451','name' => 'Dr M.G.AZAM','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '452','doctor_id' => 'RX-DR-452','name' => 'Dr A.K.S ZAHID MAHMUD KHAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '453','doctor_id' => 'RX-DR-453','name' => 'PROF. FAKRUL ISLAM ','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '454','doctor_id' => 'RX-DR-454','name' => 'PROF. QUZI MOHIBUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '455','doctor_id' => 'RX-DR-455','name' => 'Dr ARUN KUMAR SARMA','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '456','doctor_id' => 'RX-DR-456','name' => 'Dr ROWNAK JAHAN TAMANNA','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '457','doctor_id' => 'RX-DR-457','name' => 'Dr FARHAD UDDIN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '458','doctor_id' => 'RX-DR-458','name' => 'Dr ELIASH ALI','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '459','doctor_id' => 'RX-DR-459','name' => 'Dr M.A. MANAN ','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '460','doctor_id' => 'RX-DR-460','name' => 'Dr BADRUL HAQUE','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '461','doctor_id' => 'RX-DR-461','name' => 'Dr FAZLUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '462','doctor_id' => 'RX-DR-462','name' => 'PROF. Dr MD. FARUQUE ','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '463','doctor_id' => 'RX-DR-463','name' => 'PROF. MUNSHI MUJIBUR RAHMAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '464','doctor_id' => 'RX-DR-464','name' => 'Dr SIRAJUL HAQUE','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '465','doctor_id' => 'RX-DR-465','name' => 'Dr MAHMUDUR RAHMAN SIDDIQUI','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '466','doctor_id' => 'RX-DR-466','name' => 'DrNAHID MORSHED','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '467','doctor_id' => 'RX-DR-467','name' => 'PROF. FIROZ AHMED QURAISHI','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '468','doctor_id' => 'RX-DR-468','name' => 'Dr RAYAN ANIS ','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '469','doctor_id' => 'RX-DR-469','name' => 'PROF. A.K.M AMINUL HAQUE','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '470','doctor_id' => 'RX-DR-470','name' => 'DrABDUL KADER AKANDA','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '471','doctor_id' => 'RX-DR-471','name' => 'Dr ONI','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '472','doctor_id' => 'RX-DR-472','name' => 'Dr MAHIN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '473','doctor_id' => 'RX-DR-473','name' => 'Dr ARIKA','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '474','doctor_id' => 'RX-DR-474','name' => 'Dr RIFAT','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '475','doctor_id' => 'RX-DR-475','name' => 'Dr TANJANA','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '476','doctor_id' => 'RX-DR-476','name' => 'Dr BORHAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '477','doctor_id' => 'RX-DR-477','name' => 'Dr SAJJAD','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '478','doctor_id' => 'RX-DR-478','name' => 'Dr YUSUF','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '479','doctor_id' => 'RX-DR-479','name' => 'Dr SOJIB','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '480','doctor_id' => 'RX-DR-480','name' => 'Dr ORIAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '481','doctor_id' => 'RX-DR-481','name' => 'Dr EMRAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '482','doctor_id' => 'RX-DR-482','name' => 'Dr FOYSAL','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '483','doctor_id' => 'RX-DR-483','name' => 'Dr SIFAT','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '484','doctor_id' => 'RX-DR-484','name' => 'Dr ATIQ','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '485','doctor_id' => 'RX-DR-485','name' => 'Dr ANHAR','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '486','doctor_id' => 'RX-DR-486','name' => 'Dr MURAD','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '487','doctor_id' => 'RX-DR-487','name' => 'Dr MILON','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '488','doctor_id' => 'RX-DR-488','name' => 'Dr IQBAL KAZI','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '489','doctor_id' => 'RX-DR-489','name' => 'DrRAJIBUL ALAM','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '490','doctor_id' => 'RX-DR-490','name' => 'PROF. AZIZUL HAQUE','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '491','doctor_id' => 'RX-DR-491','name' => 'Dr NUROZZAMAN KHAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '492','doctor_id' => 'RX-DR-492','name' => 'PROF. SHEIK NESAR UDDIN AHMED','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '493','doctor_id' => 'RX-DR-493','name' => 'Dr P.P DAY','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '494','doctor_id' => 'RX-DR-494','name' => 'Dr NAZMUL ISLAM','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '495','doctor_id' => 'RX-DR-495','name' => 'DrM.MONIRUZZAMAN','mobile_no' => '880','pso_ffc' => 'I34'),
            array('id' => '496','doctor_id' => 'RX-DR-496','name' => 'Prof. DrMd. Nur Hossain','mobile_no' => '880','pso_ffc' => 'I72'),
            array('id' => '497','doctor_id' => 'RX-DR-497','name' => 'Prof. DrMd. Sayed Azizul Haque','mobile_no' => '880','pso_ffc' => 'I72'),
            array('id' => '498','doctor_id' => 'RX-DR-498','name' => 'Prof. Dr Md. Rafiqul Islam','mobile_no' => '880','pso_ffc' => 'I72'),
            array('id' => '499','doctor_id' => 'RX-DR-499','name' => 'Prof. Brig. Dr Md Abdur Razzak','mobile_no' => '880','pso_ffc' => 'I72'),
            array('id' => '500','doctor_id' => 'RX-DR-500','name' => 'Dr Md. Dabir Hossain','mobile_no' => '880','pso_ffc' => 'I72'),
            array('id' => '501','doctor_id' => 'RX-DR-501','name' => 'Dr Rahamatul Bari','mobile_no' => '880','pso_ffc' => 'I72'),
            array('id' => '502','doctor_id' => 'RX-DR-502','name' => 'Dr M. A. Kashem','mobile_no' => '880','pso_ffc' => 'I72'),
        );

        DoctorList::insert($doctor_list);
    }
}
